// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLmn9NfN6rUeIClbjPob8pNJ7cSnc0_ig',
    appId: '1:1073479504219:web:e5317e9ac5adb407414a7e',
    messagingSenderId: '1073479504219',
    projectId: 'notex-d1cc5',
    authDomain: 'notex-d1cc5.firebaseapp.com',
    storageBucket: 'notex-d1cc5.firebasestorage.app',
    measurementId: 'G-NQ2MK80RMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNbnXxAiGWpB7Dfz3kKbTGL2E1eto7T-I',
    appId: '1:1073479504219:android:40fe1aa070738f19414a7e',
    messagingSenderId: '1073479504219',
    projectId: 'notex-d1cc5',
    storageBucket: 'notex-d1cc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUNywlyA0s0fthQoHG91O4D5pYDM8B4dg',
    appId: '1:1073479504219:ios:9674d49ca35af121414a7e',
    messagingSenderId: '1073479504219',
    projectId: 'notex-d1cc5',
    storageBucket: 'notex-d1cc5.firebasestorage.app',
    androidClientId: '1073479504219-3b8gvibcillftlnbt8t7mcjljvn1nb67.apps.googleusercontent.com',
    iosClientId: '1073479504219-uu975hbm79pgqs493j965i77gmfghnr1.apps.googleusercontent.com',
    iosBundleId: 'com.example.notex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUNywlyA0s0fthQoHG91O4D5pYDM8B4dg',
    appId: '1:1073479504219:ios:9674d49ca35af121414a7e',
    messagingSenderId: '1073479504219',
    projectId: 'notex-d1cc5',
    storageBucket: 'notex-d1cc5.firebasestorage.app',
    androidClientId: '1073479504219-3b8gvibcillftlnbt8t7mcjljvn1nb67.apps.googleusercontent.com',
    iosClientId: '1073479504219-uu975hbm79pgqs493j965i77gmfghnr1.apps.googleusercontent.com',
    iosBundleId: 'com.example.notex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLmn9NfN6rUeIClbjPob8pNJ7cSnc0_ig',
    appId: '1:1073479504219:web:0d330e5084ffd665414a7e',
    messagingSenderId: '1073479504219',
    projectId: 'notex-d1cc5',
    authDomain: 'notex-d1cc5.firebaseapp.com',
    storageBucket: 'notex-d1cc5.firebasestorage.app',
    measurementId: 'G-TY46QVNF5B',
  );
}
