name: notex
description: "An app for sharing notes and other stuffs"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.1.2
  firebase_auth: 5.5.1
  cloud_firestore: ^5.6.5
  cupertino_icons: ^1.0.2
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4
  file_picker: ^9.1.0
  url_launcher: ^6.3.1
  flutter_pdfview: ^1.4.0
  path_provider: ^2.1.5
  syncfusion_flutter_pdfviewer: ^29.1.33
  http: ^1.3.0
  share_plus: ^10.1.4
  google_sign_in: ^6.2.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Boldonse
      fonts:
        - asset: fonts/Boldonse-Regular.ttf
        - asset: fonts/Boldonse-Bold.ttf
          weight: 700
        - asset: fonts/Boldonse-Medium.ttf
          weight: 500
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-Regular.ttf
        - asset: fonts/Oswald-Bold.ttf
          weight: 700
        - asset: fonts/Oswald-Medium.ttf
          weight: 500
        - asset: fonts/Oswald-Light.ttf
          weight: 300