name: notex
description: "An app for sharing notes and other stuffs"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  firebase_auth: 5.5.1
  cloud_firestore: ^5.6.5
  cupertino_icons: ^1.0.2
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4
  file_picker: ^9.1.0
  url_launcher: ^6.3.1
  flutter_pdfview: ^1.4.0
  path_provider: ^2.1.5
  syncfusion_flutter_pdfviewer: ^29.1.33
  http: ^1.3.0
  share_plus: ^10.1.4
  google_sign_in: ^6.2.1
  google_fonts: ^6.2.1
  fl_chart: ^0.70.2
  googleapis: any
  googleapis_auth: any
  ntp: ^2.0.0
  shared_preferences: 2.5.3
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - keys.env
    - icons/bell.png
    - images/arka.png
    - images/login.jpg
    - images/right-arrow.png
  fonts:
    - family: Roboto
      fonts:
      - asset: fonts/Roboto_Regular.ttf
      - asset: fonts/Roboto_Bold.ttf
        weight: 700
    - family: Boldonse
      fonts:
        - asset: fonts/Boldonse-Regular.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
    - family: KoPubBatang
      fonts:
        - asset: fonts/KoPubBatang-Regular.ttf
          weight: 400
    - family: porterssans
      fonts:
        - asset: fonts/porter-sans-inline-block.ttf
          weight: 400
    - family: anton    
      fonts:
        - asset: fonts/Anton-Regular.ttf
          weight: 400